# Generated by Django 4.0.5 on 2022-06-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name_plural': 'Editoras'},
        ),
    ]
