# Generated by Django 4.1 on 2022-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usuario_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="name",
        ),
        migrations.AddField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
