# Generated by Django 4.1 on 2022-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_usuario_name_usuario_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="rg",
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
